Matchh-master/src/Web/Match.Portal.Web/Controllers/GeneralSummaryController.cs
using System.Net.Http.Json;
using Match.Business.Constants;
using Match.Business.Constants.Enums;
using Match.Business.Services;
using Match.Core.Utilities.Results;
using Match.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Match.Business.Helper;


namespace Match.Web.Controllers
{
    public class GeneralSummaryController : BaseController
    {
        private readonly IReportService _repoReportService;
        private readonly ILogger<HomeController> _logger;

        public GeneralSummaryController(IReportService repoReportService, ILogger<HomeController> logger)
        {
            _repoReportService = repoReportService;
            _logger = logger;
        }



        //Genel Durum FP-01-01			
        public async Task<IActionResult> GeneralSum()
        {
            var result = await _repoReportService.GetReportFP_01_01Async();
            var reportInfoList = new GeneralSumModel();
            if (result != null && result.Any())
            {
                reportInfoList.Assets = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-01-001")?.Price ?? 0).ToString("n2");
                reportInfoList.Stocks = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-01-002")?.Price ?? 0).ToString("n2");
                reportInfoList.WillReceive = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-01-003")?.Price ?? 0).ToString("n2");
                reportInfoList.Debt = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-01-004")?.Price ?? 0).ToString("n2");
                #region ### S01-E5-02-005 Kasa-Banka-Çek-Senet-Pos ###
                var kasaBankaCekSenetPosData = new List<SeriesData>();
                var walletData = result.Where(a => a.DisplayId == "S01-E5-02-005").ToList();
                var displayNames = walletData.Select(a => a.DisplayTitle).Distinct().ToList();

                foreach (var displayName in displayNames)
                {
                    var chartData = new SeriesData();
                    chartData.name = displayName;
                    var itemData = new double[12];

                    var items = walletData.Where(a => a.DisplayTitle == displayName).ToList();
                    for (int i = 1; i < 13; i++)
                    {
                        var item = items.FirstOrDefault(a => a.ReportMonth == i);
                        if (item != null)
                        {
                            itemData[i - 1] = item.Price;
                        }
                        else
                        {
                            itemData[i - 1] = 0;
                        }

                    }
                    chartData.data = itemData;
                    kasaBankaCekSenetPosData.Add(chartData);
                }
                reportInfoList.KasaBankaCekSenetPos = kasaBankaCekSenetPosData;
                #endregion

                #region ### Vadesi Geçen - Geçmeyen Borç Alacaklar ###

                var vadesiGGBorcAlacakData = new List<SeriesData>();
                var yearList = new List<int>();
                var vadesiGGBorcAlacakDataIds = new List<string>() { "S01-E5-02-007-01", "S01-E5-02-007-02", "S01-E5-02-007-03", "S01-E5-02-007-04" };

                var debtData = result.Where(a => vadesiGGBorcAlacakDataIds.Contains(a.DisplayId)).ToList();

                foreach (var item in debtData)
                {
                    var chartData = new SeriesData();
                    chartData.name = item.DisplayTitle;
                    chartData.data = new double[1] { item.Price };

                    vadesiGGBorcAlacakData.Add(chartData);
                    yearList.Add(Convert.ToInt32(item.ReportYear));

                }

                var vadesiGGBorcAlacak = new MaturityDebt();
                vadesiGGBorcAlacak.Data = vadesiGGBorcAlacakData;
                vadesiGGBorcAlacak.Years = yearList.Distinct().ToArray();

                reportInfoList.VadesiGecenGecmeyenBorcAlacak = vadesiGGBorcAlacak;

                #endregion

                #region ### Satışlar ###
                //Satışlar                      S01-E5-03-008-01
                //Aylık Satışlar Grafiği        S01-E5-03-008-02
                //Değişim % 'si					S01-E5-03-008-04
                var satislar = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-008-01")?.Price ?? 0).ToString("n2");
                var degisim = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-008-04")?.Price ?? 0).ToString();

                var satislarData = new List<SeriesData>();
                var satislarResult = result.Where(a => a.DisplayId == "S01-E5-03-008-02").ToList();
                var chartDataSatislar = new SeriesData();
                var itemDataSatislar = new double[12];
                var satislarModel = new SatislarData();

                for (int i = 1; i < 13; i++)
                {
                    var itemSatislar = satislarResult.FirstOrDefault(a => a.ReportMonth == i);
                    if (itemSatislar != null)
                    {
                        itemDataSatislar[i - 1] = itemSatislar.Price;
                    }
                    else
                    {
                        itemDataSatislar[i - 1] = 0;
                    }

                }
                chartDataSatislar.data = itemDataSatislar;
                chartDataSatislar.name = (satislarResult.FirstOrDefault()?.DisplayTitle ?? "");
                satislarData.Add(chartDataSatislar);

                satislarModel.ChartData = satislarData;
                satislarModel.Satislar = satislar;
                satislarModel.Degisim = degisim;

                reportInfoList.Satislar = satislarModel;

                #endregion
                #region ### Satışların Maliyeti ###
                //Satışların Maliyeti  S01-E5-03-009-01
                //Aylık Grafik         S01-E5-03-009-02
                //Değişim % 'si        S01-E5-03-009-04
                var satislarMaliyet = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-009-01")?.Price ?? 0).ToString("n2");
                var degisimrMaliyet = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-009-04")?.Price ?? 0).ToString();

                var satislarrMaliyetData = new List<SeriesData>();
                var satislarMaliyetResult = result.Where(a => a.DisplayId == "S01-E5-03-009-02").ToList();
                var chartDataSatislarMaliyet = new SeriesData();
                var itemDataSatislarMaliyet = new double[12];
                var satislarMaliyetModel = new SatislarData();

                for (int i = 1; i < 13; i++)
                {
                    var itemSatislar = satislarResult.FirstOrDefault(a => a.ReportMonth == i);
                    if (itemSatislar != null)
                    {
                        itemDataSatislarMaliyet[i - 1] = itemSatislar.Price;
                    }
                    else
                    {
                        itemDataSatislarMaliyet[i - 1] = 0;
                    }

                }
                chartDataSatislarMaliyet.data = itemDataSatislar;
                chartDataSatislarMaliyet.name = (satislarResult.FirstOrDefault()?.DisplayTitle ?? "");
                satislarrMaliyetData.Add(chartDataSatislar);

                satislarMaliyetModel.ChartData = satislarrMaliyetData;
                satislarMaliyetModel.Satislar = satislarMaliyet;
                satislarMaliyetModel.Degisim = degisimrMaliyet;

                reportInfoList.SatislarinMaliyeti = satislarMaliyetModel;

                #endregion
                #region ### Satışlar Brüt Kar ###
                //Brüt Kar      S01-E5-03-010-01
                //Aylık Grafik  S01-E5-03-010-02
                //Değişim % 'si S01-E5-03-010-04
                var satislarBrutKar = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-010-01")?.Price ?? 0).ToString("n2");
                var degisimBrutKar = (result.FirstOrDefault(a => a.DisplayId == "S01-E5-03-010-04")?.Price ?? 0).ToString();

                var satislarBrutKarData = new List<SeriesData>();
                var satislarBrutKarResult = result.Where(a => a.DisplayId == "S01-E5-03-010-02").ToList();
                var chartDataSatislarBrutKar = new SeriesData();
                var itemDataSatislarBrutKar = new double[12];
                var satislarBrutKarModel = new SatislarData();

                for (int i = 1; i < 13; i++)
                {
                    var itemSatislar = satislarResult.FirstOrDefault(a => a.ReportMonth == i);
                    if (itemSatislar != null)
                    {
                        itemDataSatislarBrutKar[i - 1] = itemSatislar.Price;
                    }
                    else
                    {
                        itemDataSatislarBrutKar[i - 1] = 0;
                    }

                }
                chartDataSatislarBrutKar.data = itemDataSatislar;
                chartDataSatislarBrutKar.name = (satislarResult.FirstOrDefault()?.DisplayTitle ?? "");
                satislarBrutKarData.Add(chartDataSatislar);

                satislarBrutKarModel.ChartData = satislarBrutKarData;
                satislarBrutKarModel.Satislar = satislarBrutKar;
                satislarBrutKarModel.Degisim = degisimBrutKar;

                reportInfoList.SatislarBrutKar = satislarBrutKarModel;

                #endregion
                #region ### Stok Ana grupları toplam tutar ###
                var stoklarAnaGrupData = new List<double>();
                var stoklarAnaGrupName = new List<string>();
                var stokAnaGruplariToplamData = result.Where(a => a.DisplayId == "S01-E5-02-006").ToList();
                foreach (var item in stokAnaGruplariToplamData)
                {
                    stoklarAnaGrupData.Add(Math.Round(item.Price, 2));
                    stoklarAnaGrupName.Add(item.DisplayTitle);
                }
                var stockData = new DoubleArray();

Matchh-master/src/Web/Match.Portal.Web/Views/GeneralSummary/FinancialStatements.cshtml
@using System.Text.Json
@model FinancialStatementsModel

<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Firma Genel Durum /</span> Özet Mali Tablolar</h4>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <h5 class="card-header">Özet Mali Tablolar</h5>

            <hr class="my-0" />
            <div class="card-body">
                <div class="row">
                    @using (Html.BeginForm("FinancialStatements", "GeneralSummary", FormMethod.Post))
                    {
                        <div class="row mb-4">
                            <div class="row">
                                <div class="mb-3 col-md-6">
                                    <label class="form-label" for="ReportTypeId">Rapor Tipi</label>
                                    <select id="ReportTypeId" class="form-control select2" asp-for="ReportTypeId"
                                        aria-label="ReportTypeId">
                                        <option value="1">Yıllık</option>
                                        <option value="2">Aylık</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="mb-3 col-md-6">
                                    <label for="CariDonemDate" class="form-label">Cari Dönem</label>
                                    <input class="form-control onlyMontPicker" type="text" name="CariDonemDate"
                                        id="CariDonemDate" value="@Model.CariDonemDate" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="OncekiDonemDate" class="form-label">Önceki Dönem</label>
                                    <input class="form-control onlyMontPicker" type="text" id="OncekiDonemDate"
                                        name="OncekiDonemDate" value="@Model.OncekiDonemDate" />

                                </div>
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2">Sorgula</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="row mb-4">


            <div class="col-md-6 col-lg-6 order-2 mb-6">
                <div class="card h-100">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Aktifler</th>
                                <th>Önceki Dönem</th>
                                <th>Cari Dönem</th>
                                <th>Değ %</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            @foreach (var b in Model.Aktifler)
                            {
                                <tr>
                                    <td>@b.Title</td>
                                    <td>@b.Data.OncekiDonem</td>
                                    <td>@b.Data.CariDonem</td>
                                    <td><span class="badge link-warning me-1">@b.Data.Degisim</span></td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-md-6 col-lg-6 order-2 mb-6">
                <div class="card h-100">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Aktifler</th>
                                <th>Önceki Dönem</th>
                                <th>Cari Dönem</th>
                                <th>Değ %</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            @foreach (var b in Model.Pasifler)
                            {
                                <tr>
                                    <td>@b.Title</td>
                                    <td>@b.Data.OncekiDonem</td>
                                    <td>@b.Data.CariDonem</td>
                                    <td><span class="badge link-warning me-1">@b.Data.Degisim</span></td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-md-12 col-lg-12 order-2 mb-6">
                <div class="card h-100">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Özet Gelir Tablosu</th>
                                <th>Önceki Dönem</th>
                                <th>NS %</th>
                                <th>Cari Dönem</th>
                                <th>NS %</th>
                                <th>Büyüme %%</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            @foreach (var b in Model.Ozetler)
                            {
                                <tr>
                                    <td>@b.Title</td>
                                    <td>@b.Data.OncekiDonem</td>
                                    <td><span class="badge link-warning me-1">@b.Data.OncekiDonemNS</span></td>
                                    <td>@b.Data.CariDonem</td>
                                    <td><span class="badge link-danger me-1">@b.Data.CariDonemNS</span></td>
                                    <td><span class="badge link-success me-1">@b.Data.Degisim</span></td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {

            // Yalnızca sayı ve slash (/) karakterlerine izin verme
            $('#cariDonemDate').on('keypress', function (e) {
                var charCode = e.which;

                // Yalnızca sayı (0-9) ve slash (/) karakterleri kabul edilecek
                if (!(charCode >= 48 && charCode <= 57) && charCode !== 47) {
                    e.preventDefault();
                    alert("Lütfen sadece sayılar ve '/' karakterini kullanın.");
                }
            });
        });

    </script>


}